### ISSUE TITLE
[BUG] Can't scan my qr code

### ISSUE THREAD

**Issue by AMHKillarney** [clawfire/covid19-passbook-generator#102]
### What happened?

I have an iPhone 8 and am unable to scan my EU digital cert using the 
COVID-19Passbook.netlify.app

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there. Are you opening safari and pasting the link or are you opening it from another app like Facebook, Messenger, Instagram ... ? 

What's doesn't work? 
Can you press the scan blue button and see the video feed? Or not? 

If yes, did you try then a better lightning ?

**Comment by AMHKillarney** [comment]
I am opening Safari and typing in

https://covid19passbook.netlify.app

It opens up and there is a blue box with the words

   Start Scanning

Which I pressed then it leads me into another webpage which says

Aim at the QR Code of your certificate to capture.

But it does not access the camera on my iPhone or request to access the
camera so am unable to see the video feed!

**Comment by clawfire** [comment]
Thanks for the details. 

Can you check if you never disallow Safari to access your camera in the past? Here's how to do it

1. Go on Settings
2. Select Safari
3. Scroll all the way down, and select Camera
4. It should be on "ask" or "Allow". 

If it's on Deny, it's because you forbid Safari to access your camera in the past and I cannot do anything from a web app to detect it or automatically redirect you to change that (like a native app could).

**Comment by AMHKillarney** [comment]
Sorted
Thanks for your help
