### ISSUE TITLE
Interface optimisation

### ISSUE THREAD

**Issue by n00d1e5** [clawfire/covid19-passbook-generator#299]
### Describe the solution you'd like

1. Increase the space (left margin) before the title. The title "Eu Digital COVID Certificate" not aligned with the following subheadings.

2. Now, some countries started the third dose of the vaccine. However, in the details of the vaccination type pass, the format is "2/2", this should be further investigated (I will check the EU DCC guideline later).

3. How about removing "Show this when requested" under the QR code, then, let the QR code show in the white square without too much blank margin.

### Anything else?

@clawfire I send you an email, maybe it went to Spam. Could you please check with the keyword "n00d1e5", please? Look forward to your reply.

**Comment by clawfire** [comment]
Hey there. 
Thanks for your suggestions. Some thoughts : 

1. Where ? Of it's on the passbook itself i have no control whatsoever on the rendering. Every app (not just apple wallet) render it their own way. The only control is alignment. Left, right, center. That's it. 

2. I just use the data from the pass. Garbage in, garbage out. If the country issue a badly formated document, I'm not changing it. 

3. I can check on removing the text, but again I have no control over the display and probably you'll still have the border because that's how apple wants it 🤷🏻‍♂️

**Comment by n00d1e5** [comment]
About the point 2, I agree what you said. Hope they will have a general policy soon. :)

Here's several examples in my wallet. The title of EU DCC is furthest to the left, although other passes use logos as the title so as to have a better interface, could we add spaces to take up space before the name (or of course change the title to a vector image).

![](https://z3.ax1x.com/2021/11/05/IKVJDf.jpg)
![](https://z3.ax1x.com/2021/11/05/IKVGKP.jpg)

I took one boarding pass as an example. First, the left margins are the same for all elements (including title and sub-headers). Second, there is no text under the QR code, personally, I think it is much better to have a square box around the QR code instead of a rectangular.

![](https://z3.ax1x.com/2021/11/05/IKV3vt.jpg)

**Comment by Trefex** [comment]
Just saw your point 3 after creating a dedicated issue for this: https://github.com/clawfire/covid19-passbook-generator/issues/302
