### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Locky103** [clawfire/covid19-passbook-generator#374]
### Contact Details

Jloughran104@gmail.com

### What happened?

A bug happened! My covid cert wont scan to my wallet it freezes when you try tis on app

### What browsers are you seeing the problem on?

Chrome, Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there

Well, first, on an iPhone you'll NEED to use Safari. No other browser have access to your wallet, Apple had designed it that way. That's why we put a message when you first access the site / app to ask you to use Safari on iOS 😃 

When does it freeze? Before scanning, after scanning, when trying to save to wallet?
