### ISSUE TITLE
[Feature request] Toggle visibility of the certificate type

### ISSUE THREAD

**Issue by ojura** [clawfire/covid19-passbook-generator#51]
Some official covid check apps (eg: Italy’s VerificaC19) are very privacy oriented. They do not show the user’s medical history (such as grounds for the certificate - vaccination/recovery/test) — the only thing displayed is whether the certificate satisfies Italy’s rules.  The logic for verifying this obviously has access to the certificate content, but it is not shown to the verification app user. It looks like this:

![FF672326-7387-47E7-9152-95270B6F7E3E](https://user-images.githubusercontent.com/9062353/124676839-91baf280-debf-11eb-9ab2-8ca1c7ec54f1.jpeg)

Therefore, for maximum privacy, we could opt to hide the reason for the certificate in the pass.

**Comment by clawfire** [comment]
Hey @ojura, thanks for the feature request.

In fact, at first, we didn't have it on the front of the certificate. But I find it difficult to then know which certificate to use when you have multiple (Luxembourg test the population like every month or two months, so we have test results + vaccination + recovery for some ... that's 2 or 3 certificates at the same time 😂 ).

Since the information may be required for traveling, would you be comfortable to an option to move the test type into the back of the card with all the other details instead? Doing so, you can always decide to reveal the information if needed.

**Comment by clawfire** [comment]
I think we have something like #104 who could be related to this. The ability to select information to display or not.

**Comment by clawfire** [comment]
Had the case today again in Germany where no ones is equipped to scan the pass and rely on checking the information. Hiding such info would make the pass unusable. At that time, the way the pass is created use the ID of the certificate as a unique ID so you cannot have two different versions of the same pass.

**Comment by ojura** [comment]
I didn't mean to hide it completely, just to move it to the "details" screen. So it would be just like the paper one -- if you want, you can unfold it and show it what's inside.

**Comment by clawfire** [comment]
To date, the informations on the front of the pass are the one you have on paper one, and the ones on the details screen are the one you have "inside" of the paper one. The only difference is I put the type of certificate because if you have multiple passes you may need to be able to select the correct one without having to go through details of every passes (which are only accessible from the wallet app, phone unlocked). 

But being able to tailor which information appears where shouldn't be a big deal I guess. Just need something like a "pass editor" we don't have now.
