### ISSUE TITLE
[BUG] Number of vaccinations/doses does not match certificate

### ISSUE THREAD

**Issue by alvarojme** [clawfire/covid19-passbook-generator#64]
### Contact Details

alvarojme@gmail.com

### What happened?

A bug happened! I have successfully imported my certificate to my iPhone wallet. However, when I go into the card details, the field “Number in a series of vaccination / doses (…)” does not match my certificate. It reads 1/2, while it should say 1/1.

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hello again 😃 

I checked the code, and I'm using the `dn` and `sd` informations from the pass. so that means your pass may contain wrong informations. Do you had a J&J shot or you got only 1 because of a recovery from COVID?

**Comment by alvarojme** [comment]
Hi! I got just 1 Pfizer (Comirnaty) because of a recovery. Both my official
documents and the PDF certificate say 1/1 in plain text, but perhaps they
have forgotten to generate the right QR...

**Comment by clawfire** [comment]
I emailed you if you want to share the code I can check it out. I would be also intersted to see how it behave on validation apps such as https://apps.apple.com/lu/app/covidcheck-lu/id1570218766

**Comment by alvarojme** [comment]
Same issue with covidcheck :-( Apparently, the region in which I live has
failed to produce the right QR certificate...

**Comment by clawfire** [comment]
Trust me, that's more common than you think. Luxembourg sticks with 2 shoots instead of just one, and we are so glad so far. 

So ... there's nothing I can do for you since your pass data are the ones I read. It's just your PDF that lies 😂 . With cross vaccination coming their way, I'm sure we gonna have all of those. I had UK people having two separate vaccine certificates in the same QR code. One for product A shot 1, one for product B shot 1 😁  That's 2 shots. And that's a valid vaccine scheme. However, most of the apps just read the first one only. And if they read both, they still see just the first shot, so it still fails 😫

I would recommend asking your local authority to redo your certificate properly. Which country is it? just out of curiosity.

**Comment by alvarojme** [comment]
Thank you, Thibault. This is Spain, region of Madrid. I’ll see if I can do
something about it with local authorities.

Best,

Alvaro
