### ISSUE TITLE
[feature request] UK skin version

### ISSUE THREAD

**Issue by twolfer** [clawfire/covid19-passbook-generator#65]
### Contact Details

twolfer@gmail.com

### Is your feature request related to a problem? Please describe.

Having the UK QR code saying it’s from EU will make it look fake. 

### Describe the solution you'd like

No need to change the colours. It just need to say “UK” instead of “EU” on the main title and have this flag:
https://commons.m.wikimedia.org/wiki/File:Square_Flag_of_the_United_Kingdom.svg

### Anything else?

Please and thank you. ( ๑❛._❛ )

**Comment by grischard** [comment]
Thanks! We should do this for Swiss certificates too.

https://commons.wikimedia.org/wiki/File:Flag_of_Switzerland.svg (with a very Swiss discussion page on what the 'right' shade of red should be)

**Comment by MentalGear** [comment]
Also please for german certificates.

**Comment by twolfer** [comment]
Apologies but this is no longer needed in the UK, the app that generates it also creates passbook tickets. Thank you for your creation regardless. ( ๑❛._❛ )

**Comment by clawfire** [comment]
@twolfer hey I saw that 😃  It's good news for you in England. But is it available all the UK? I read online it's just for England.

**Comment by clawfire** [comment]
I implemented another skin for doctor anytime (side project which finance translation and some other features here) and it's really complicated. Changing the skin results in :

- adding resources for that new version
- implement another "template" for the passbook with the new skin
- implement another signature method (since we are not blindly signing anything) for that particular skin. 

I think it's tricky at that time.
