### ISSUE TITLE
[BUG] QR Code on covid cert not being read

### ISSUE THREAD

**Issue by Phylshannon** [clawfire/covid19-passbook-generator#67]
The QR code on my covid cert wont register when i am trying to set up my covid19passbook

**Comment by clawfire** [comment]
Hey 😃 
What phone or computer are you using ?
Which browser are you using ?
Did you try the app from a "in app" browser from Instagram, Facebook, Messenger, WhatsApp, ... or went to open a proper browser? 

Thanks for your answers 😃

**Comment by DanielBrierton** [comment]
I was also unable to scan my QR code.

Country: Ireland
Device: iPhone XR
OS: iOS 15 dev beta 3
Browser: Safari (both standalone and in app)

Was able to use a picture to get it done in the end though.

**Comment by clawfire** [comment]
Weird. Seems I have issues with iPhones Xr :/ 

Was the light exposition good? I mean some iPhones don't like bad lighting, especially with the highly density of the information in the code. 

Since you have ios15 dev beta, could I ask you If there's any error in the safari console when it fail to work ?
