### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jarv1sss** [clawfire/covid19-passbook-generator#68]
iPhone X. iOS 13.5. Pressing scan or upload doesn’t do anything. On other phones it’ll ask for camera access or upload option will give 3 possible options but nothing at all happens on this phone. I’ve cleared safari cache etc. I’ve also tried on chrome and duck duck so even though I know I couldn’t import to wallet using those browsers but the same initial issue occurs in there too.

**Comment by clawfire** [comment]
🤔  That's weird. Camera access should work perfectly on chrome. I had to use a trick for safari (which doesn't support natively QR code API in the browser). 

Is it possible your phone is enrolled in mobile device management from a corporation? some prevent access to camera through safari with policies and I cannot do anything about it (that's the point of the policy 😅)

**Comment by clawfire** [comment]
Found out the bug was caused by the lack of support of BigInt in Safari before version 14. And there's no polyfill we can put in place to support this. BigInt represents big integer numbers in memory, required for cryptographic manipulation such as decoding the QR code.

I implemented a detection feature of lack of this functionality and warned the user with a message + prevent to discard the message (since the app will be totally unusable anyway).

iPhones 6 and 6+ are all stuck in iOS12 max, which isn't supported.
IPhones after 6 (including 6s) can upgrade to iOS14 and should ti get the app working.
