### ISSUE TITLE
[BUG] Can't scan the qrcode

### ISSUE THREAD

**Issue by GQuinn5** [clawfire/covid19-passbook-generator#77]
Hi , when I try to scan my COVID Digital Passport I keep getting a message saying No QR Code Detected. I have tried scanning the passport on 2 devices multiple times and got the same message each time. Can you resend it or offer any other assistance

**Comment by clawfire** [comment]
Hello 😃 
First of all, there's no message with the scanner function when no code is detected, only on the upload screenshot function.

1. if you use the upload function, please be sure you made a screenshot of the qrcode and not the entire page. Otherwise, due to your phone screen resolution, the qrcode cannot be read
2. if you're using the scanner, are you sure it's my app ? 😁  Because I don't have such message.

Any way, if you want, you can send me to hello@thibaultmilan.com your qrcode and I can see if somethings wrong with it.

Cheers

**Comment by GQuinn5** [comment]
Hi
I was able to sort it thanks. Close this action please

Regards

Gerry
